### ISSUE TITLE
A Bug

### ISSUE THREAD

**Issue by zhangdahua1** [yg-smile/RL_VVC_dataset#1]
Dear author.
Thank you very much for the work of the author, which is very helpful to my study. But I encountered a bug in the process of learning --- oserror:/ data/processed/first_ 2897_ ami_ aggto_ 580.csv not found. So could this folder named processed and raw be uploaded or shared?

**Comment by yg-smile** [comment]
Dear @zhangdahua1 ,
Thank you. The file data/processed.zip has been pushed to the repo. Please download and unzip this file. The path after unzipping must be data/processed/... 
Please let me know if there are other issues.

**Comment by zhangdahua1** [comment]
Thank you for your reply. I'll download it again. I have another question. Does your program have any requirements for the operating system, windows or Linux

**Comment by yg-smile** [comment]
I use the code on my Ubuntu 20.04... I think Windows is also fine. Let me know if you find errors...

**Comment by zhangdahua1** [comment]
I use it on Windows,it have some errors that "RuntimeError: Failed to process string with tex because latex could not be found".I'll try to fix this problem again or change a computer.If it can't be solved, I'll contact you again
Thank you very much.

**Comment by yg-smile** [comment]
Did you run the plot.py? Please comment out line 2 and line 6-9 and see if the problem shows up again.
This is to let Matplotlib to use latex font for plotting figures.. If your system does not have Latex installed or the python couldn't find the path to it there might be that problem.

**Comment by zhangdahua1** [comment]
It can work successfull. You are really a knowledgeable and patient scholar. If I have any questions later, I will continue to ask you.

Thank you very much and wish you a happy life.
