### ISSUE TITLE
References

### ISSUE THREAD

**Issue by goruiqi** [yg-smile/RL_VVC_dataset#4]
Hello, can you tell me the reference article of this program, please?  Because I can't find the article ”A Reinforcement Learning-based Volt-VAR Control Dataset and Environment“.

**Comment by yg-smile** [comment]
Hi @goruiqi thank you. We apologize for the inconvenience. We are still working on the reference article and putting that on arXiv. I will keep you posted once it is announced.

**Comment by goruiqi** [comment]
Thank you for your reply. I wish you all the best!

**Comment by yg-smile** [comment]
Thank you. I've updated the bib information in the README.md. You can copy the bib information and have a look at the article https://arxiv.org/abs/2204.09500.

Wish you all the best.

**Comment by goruiqi** [comment]
Thank you very much. This artical help me a lot.
